### ISSUE TITLE
Allow for non-zipped JPZ

### ISSUE THREAD

**Issue by boisvert42** [jpd236/kotwords#25]
My workflow when using kotwords is invariably: 1) download JPZ 2) unzip JPZ 3) reformat XML to make it pretty-printed.  It would be wonderful if I could skip steps (2) and (3).

**Comment by jpd236** [comment]
Exporting formatted XML is probably a reasonable default. If the file is zipped by default, the extra whitespace won't make much of a difference (not that it makes much of a difference when unzipped either).

I still feel like zipping is a better default; for certain JPZs it makes a decent size difference. But an advanced setting to leave the export uncompressed would be fine with me.

**Comment by jpd236** [comment]
All forms now have a "Compress JPZ file" option, which is checked by default.

When checked, the output is the exact same as before - compressed, unformatted JPZ. The assumption here is that if you want to compress the output, you don't care about modifying the contents, so there's not much reason to pretty-print it.

When unchecked, the output is a pretty-printed XML file, with no ZIP compression, so you can view it and tweak it as desired.

I think that should cover this, but let me know if there's anything else that would be useful here!

**Comment by boisvert42** [comment]
Thanks!
