### ISSUE TITLE
Make "empty" cells instead of background-color='#FFFFFF' for acrostics 

### ISSUE THREAD

**Issue by boisvert42** [jpd236/kotwords#31]
I'm experimenting with dark mode for my solver. It would be nice not to hard-code the background color for the cells that are not part of the solution, but to make them "empty" so the software can decide what color to make them.

**Comment by jpd236** [comment]
Done. In addition to removing the background color, I had to change the type from BLOCK to VOID in order to prevent them from showing up as black squares in XWord 0.7.0.

**Comment by boisvert42** [comment]
oh, yes, that's what I meant by "empty." thanks!
