### ISSUE TITLE
Pre-populate "copyright" field with a copyright symbol

### ISSUE THREAD

**Issue by boisvert42** [jpd236/kotwords#33]
This is a stupid request but I go hunting for a copyright symbol to copy-paste whenever I use kotwords. A pre-populated symbol would save me lots of time.

**Comment by jpd236** [comment]
I'm leaning against prepopulating the field - then people who'd rather just leave copyright blank have to go and clear it.

Instead, all copyright fields now replace (c) with the copyright symbol, so you can just type it in like that. If you prefer, there's also help text below the copyright field on each page which has the symbol for easier copy-pasting.
