### ISSUE TITLE
Unhelpful error message in Two-Tone generation

### ISSUE THREAD

**Issue by Nathan-tortoise** [jpd236/kotwords#38]
I was trying to use the Two-Tone generator but I kept getting the error message "Error generating puzzle file: index: 11, size: 11". I had no idea what this message meant. Eventually I worked out that I had not removed spaces from some of the multi-word entries, so the number of entries as read by the app didn't match the number of clues. Can this error message be updated to be more helpful?

**Comment by jpd236** [comment]
Done - thanks for the suggestion.
