### ISSUE TITLE
Feature request for Eight Tracks (Advanced options)

### ISSUE THREAD

**Issue by Nathan-tortoise** [jpd236/kotwords#43]
I have a request for the advanced options for the Eight Tracks tool. I would like an option to mark the starting squares of the entries in each track after the first, with a dot or other marker that doesn't indicate which clue each one goes with. This is an option that I have used in my own puzzles as an easier alternative to the original presentation, and I have attached a sample PDF to illustrate what I mean. This isn't an urgent feature, but if it is not too difficult to implement I would appreciate it for future puzzles.
[Eight Tracks 202410 regular.pdf](https://github.com/user-attachments/files/17481175/Eight.Tracks.202410.regular.pdf)

**Comment by jpd236** [comment]
Added advanced option "Mark starting squares of entries in inner tracks". Let me know if you have any feedback. Thanks!

**Comment by Nathan-tortoise** [comment]
That looks great. Thanks!
