### ISSUE TITLE
Letter verification for creating Spiral puzzles doesn't handle newlines properly

### ISSUE THREAD

**Issue by Nathan-tortoise** [jpd236/kotwords#5]
When creating a Spiral puzzle, if the answers in either direction are entered separated by newlines, attempting to generate the JPZ gives `Error generating JPZ: Inward answer letters must be the outward answer letters in reverse`. For example, try creating a spiral puzzle with 

> `PEEL`
> `SPEED`

 as Inward entries and 

> `DEEP`
> `SLEEP`

 as outward entries, and you will get this error. Replacing the newline characters with spaces yields a valid JPZ. Since the help text says `In sequential order, separated by whitespace.` newlines should be valid separators.

**Comment by jpd236** [comment]
Thanks so much for the report, and sorry for the trouble! Glad you were able to find a way to move forward despite the bug.

All of the forms which specified "separated by whitespace" should now handle any whitespace as a separator, not just regular spaces. Please let me know if you run into any further issues.
